### ISSUE TITLE
[Possible bug?] Trakt liked lists are not self updating

### ISSUE THREAD

**Issue by rizreflects** [Tikipeter/tikipeter.github.io#134] opened 2024-10-01 13:48 UTC
Hey Peter, I hope you're keeping well. Over the past month I've ran into a problem where my Trakt liked lists are not updating on its own. This is the particular list I have set on my homescreen as a widget https://trakt.tv/users/giladg/lists/latest-releases?sort=added,asc 

The only way to get this list to update is to manually clear the trakt cache. I've been having to do this regularly this past month or the list doesn't seem to update at all, even when restarting kodi. 

Do you know why this may be happening? I'd appreciate any help you can give me. I've attached my log so you can take a look, I'm not sure if it will help though as I've not come across any error messages popping up. 

https://paste.kodi.tv/oqoyevujun

Thanks a lot

**Comment by Tikipeter** [comment] 2024-10-01 16:46
Damn, I thought this had been fixed.

The issue is Trakt doesn't have a way to let you know that liked lists have been updated,  so it needs to be refreshed each Kodi start up.  Which I thought was now happening.

I'll sort it out.

**Comment by rizreflects** [comment] 2024-10-02 08:40
12 hours sounds more than acceptable to me. I'll keep my eye out and report back if I notice any further issues. Thanks for the fix as always Peter. You're a top dev.

**Comment by rizreflects** [comment] 2024-10-02 12:37
Just updated to the latest version. It seems I'm no longer able to access any Trakt list containing TV Shows. This applies to both my own lists and my liked lists. Lists containing movies are functioning normally though. Could you double check this on your side please?

**Comment by Tikipeter** [comment] 2024-10-02 19:17
Fixed in `1.0.84`.

**Comment by rizreflects** [comment] 2024-10-05 01:38
All is working well now so I went and closed the issue

**Closed** 2024-10-05 01:37 UTC
