### ISSUE TITLE
Final Update v2.0.01

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/tikipeter.github.io#181] opened 2024-11-23 01:15 UTC
** **EDIT: FINAL RELEASE OF FEN LIGHT HAS BEEN PUSHED. THANKS FOR THE MEMORIES AND SO LONG** **

Hi all.

After giving myself some time to think, I will be retiring from Kodi addon development.

There will be one final update to Fen Light labelled version 2.0.01, likely tomorrow.

~~This update will not include any fixes for the RD issues. Anyone who insists on using RD will need to keep an eye on the scene and start using addons that provide a way to continue using it. There are a couple of fairly easy options open to devs to get RD working again in a satisfactory way.~~

** **EDIT: REAL DEBRID WILL ONCE AGAIN BE SUPPORTED IN THE FINAL RELEASE OF FEN LIGHT.** **

The final release of Light will remove the update manager from it. Meaning it will no longer look to this github to get updates. This will allow me to safely delete this github account,  which I will do 24 hours after the final release.

Anyone using Fen (not Light)....Uninstall the addon and use something else. If you don't uninstall it, then turn off the addon manager in the settings.

Fen Light will continue to work with API keys etc,  but there is already a setting to provide your own.

There will be no coming back in 6 months like last time I left, so thank you to the users over the years who were able to be decent when asking for features or reporting issues.

Support new devs. Use a please and thank you with old devs. Give them some slack.

**Comment by rizreflects** [comment] 2024-11-23 01:26
Damn. It made me sad reading this. Thank you for all the hard work you put into Fen. You're a top dev, and it's been a pleasure following the growth of your addon. I wish you all the best for the future.

**Comment by Tikipeter** [comment] 2024-11-23 01:26
Only questions here please.

No "thank you" type posts.

**Comment by rizreflects** [comment] 2024-11-23 01:27
> Only questions here please.
> 
> No "thank you" type posts.

Sorry lol, I posted before reading this.

**Comment by Tikipeter** [comment] 2024-11-23 01:28
> > Only questions here please.
> > No "thank you" type posts.
> 
> Sorry lol, I posted before reading this.

It's cool. I deleted it since you got in first.

**Comment by bbviking** [comment] 2024-11-23 01:50
Damn that's a shame, thank you for all your continued hard work over the years!

Out of interest, what's the easy options you mentioned that could allow RD to be used?

I've been working on some small seren updates recently and I'm wondering how difficult a workaround would be to implement.

**Comment by jegitoe** [comment] 2024-11-23 01:57
Sorry to see you hang up your coat. You've left a great foundation to continue on from.

Thanks for partaking.

**Comment by Treemanintx** [comment] 2024-11-23 04:01
I'ma dope when the issue is beyond putting the dot before the com. So, when loading the correct URL into Kodi Omega (https://tikipeter github.io/packages) I receive a error message and cannot complete the configuring

**Comment by redi6** [comment] 2024-11-23 04:17
Thank you for everything you have done for this community. I have been using Kodi since the old 1channel days and fen has been the best add-on I've ever used. 

Good luck in whatever is next for you my friend.

**Comment by LooseHead-1** [comment] 2024-11-23 04:56
Your addons have been legendary. What is your position on other devs (I am absolutely not one) forking your work?

**Comment by TimboZero** [comment] 2024-11-23 05:03
@Tikipeter 
I am begging you to reconsider, Fenlight may have been popular with RD but it is so much more than just RD and has many still working (and likely to continue to do so for a long time) alternatives already in it and we love the addon and the joy it’s been to use it. I know you said no thanks post and that part wasn’t, however if you stick with your decision, I will be very very sad but also grateful for your work and skills which I have appreciated a great deal and hope you reconsider.

**Comment by Tikipeter** [comment] 2024-11-23 09:22
>Out of interest, what's the easy options you mentioned that could allow RD to be used? I've been working on some small seren updates recently and I'm wondering how difficult a workaround would be to implemen

Have a look at this [Seren github issue](https://github.com/nixgates/plugin.video.seren/issues/949)

>I'ma dope when the issue is beyond putting the dot before the com. So, when loading the correct URL into Kodi Omega (https://tikipeter/ github.io/packages) I receive a error message and cannot complete the configuring

That url is gone. You need to download the zip.

>What is your position on other devs (I am absolutely not one) forking your work?

Fork away. There are many Fen forks already floating around. Only stipulation is you must maintain, at the top of the changelog, the darkgoldenrod colored "GOD BLESS HIM AND KEEP HIM SAFE". /s


Thanks for the kind words people. It means a lot to me.

**Comment by Lancs-Pete** [comment] 2024-11-23 10:01
Have to add my thanks to you @Tikipeter

FenLight is awesome and has provided so much entertainment for me and mine (& no doubt thousands of others)

Will be sad to see you go, you will be missed.

Take care, relax and (hopefully) enjoy the extra time with those around you.

**Comment by hcgiub001** [comment] 2024-11-23 11:26
> Have to add my thanks to you @Tikipeter
> 
> FenLight is awesome and has provided so much entertainment for me and mine (& no doubt thousands of others)
> 
> Will be sad to see you go, you will be missed.
> 
> Take care, relax and (hopefully) enjoy the extra time with those around you.

Fen Light is used by over 10 million.

Peter is was a privilege and honour of  getting to share the moments you was at your peak. You're name and legacy will forever be solidified in KODI community. I hope you'll pursue other activities that bring you joy. Look after yourself and thanks for the memories and the work you put in this from me and my father. Love peace and respect

**Comment by Tikipeter** [comment] 2024-11-23 11:32
> I hope you'll pursue other activities that bring you joy.

It brought me joy to bring RD compatibility back for the pending final release of Fen Light.
The playback will be slower to start sometimes, but RD WILL WORK on the final version of Light.
It should keep Fen Light working and relevant for people who want to run it into the ground. Should work for at least a year.

I appreciate all your kind words. And not in Binary this time. :)

**Comment by hcgiub001** [comment] 2024-11-23 11:44
It's a big shock. It took me a while to understand the magnitude of your announcement. 

> RD WILL WORK 

you definitely are going out on a bang lol. I hope one day we'll cross paths again. You're the best Kodi developer we've had in every way. :)

**Comment by TwilightMercy** [comment] 2024-11-23 11:45
> It brought me joy to bring RD compatibility back for the pending final release of Fen Light. The playback will be slower to start sometimes, but RD WILL WORK on the final version of Light. 

Glad to hear :)
Any chance for one last Fen 3.2.31 RD compatibility update?

**Comment by hcgiub001** [comment] 2024-11-23 11:59
the sadness of your departure still wanes on me more than the accomplishment of your work :(
I'll miss you man

**Comment by Lancs-Pete** [comment] 2024-11-23 12:43
> > I hope you'll pursue other activities that bring you joy.
> 
> It brought me joy to bring RD compatibility back for the pending final release of Fen Light.
> The playback will be slower to start sometimes, but RD WILL WORK on the final version of Light.
> It should keep Fen Light working and relevant for people who want to run it into the ground. Should work for at least a year.
> 
> I appreciate all your kind words. And not in Binary this time. :)

Thank you for this, you truly leave a legacy behind you that is second to none

Wishing you and yours all the best in whatever you do moving firward6

**Comment by rowel07** [comment] 2024-11-23 12:58
That's sad. Thank you so much for sharing your work with us.

**Comment by borygo77** [comment] 2024-11-23 12:58
Thank you Peter!
Enjoy your time out 😉
Hope you'll come back with fresh mind and even better ideas 💡 ♥️❤️

**Comment by Scope666** [comment] 2024-11-23 14:46
Fen Lite works perfectly with RD using these settings as of right now:
![image](https://github.com/user-attachments/assets/1da9bc06-8367-4302-9c8b-b393907169b0)

**Comment by Tikipeter** [comment] 2024-11-23 14:54
>Any chance for one last Fen 3.2.31 RD compatibility update?
Done.
>Fen Light works perfectly with RD using these settings as of right now
We have different definitions of "perfectly".

**Comment by Scope666** [comment] 2024-11-23 15:01
> > Any chance for one last Fen 3.2.31 RD compatibility update?
> 
> Done.
> 
> > Fen Light works perfectly with RD using these settings as of right now
> 
> We have different definitions of "perfectly".

You got me there, just meant it was a way to still use it for now.  Thanks for everything you do.    :)

**Comment by Tikipeter** [comment] 2024-11-23 15:29
Final release of Fen Light has been pushed. Thanks for the memories and so long. I'll give 2 days to update and download the zip, and then this github account will be closed.

**Comment by GitHubSand** [comment] 2024-11-23 17:38
> Hi desperately trying to redownload fen lite before irs gone but im a rookie and struggling, Can you point me to info on how to download the zip? 

http://tikipeter.github.io/packages/plugin.video.fenlight-2.0.01.zip

**Comment by VittorioG** [comment] 2024-11-23 17:41
> > Hi desperately trying to redownload fen lite before irs gone but im a rookie and struggling, Can you point me to info on how to download the zip?
> 
> http://tikipeter.github.io/packages/plugin.video.fenlight-2.0.01.zip
> 
> And thanks for the service which you provided

This doesn't seem to be working for me 🤔 Clicking the link doesn't start a download or do anything really

**Comment by GiitLew** [comment] 2024-11-23 17:48
> > Hi desperately trying to redownload fen lite before irs gone but im a rookie and struggling, Can you point me to info on how to download the zip?
> 
> http://tikipeter.github.io/packages/plugin.video.fenlight-2.0.01.zip
> 
> And thanks for the service which you provided

Is there a way i can use this to download the zip directly to kodi on my chromecast?

**Comment by redi6** [comment] 2024-11-23 17:50
Whatever you did in version 2 to make cached searches work again is incredible. 

Incredible work as always

**Comment by GitHubSand** [comment] 2024-11-23 17:54
> > > Hi desperately trying to redownload fen lite before irs gone but im a rookie and struggling, Can you point me to info on how to download the zip?
> 
> > 
> 
> > http://tikipeter.github.io/packages/plugin.video.fenlight-2.0.01.zip
> 
> > 
> 
> > And thanks for the service which you provided
> 
> 
> 
> Is there a way i can use this to download the zip directly to kodi on my chromecast?
> 
> 

You can put the zip file on a usb and plug it in or put the zip file on google cloud and install from there on chromecast

**Comment by TimboZero** [comment] 2024-11-23 17:55
For some reason I am getting a 512KB file and I am sure as hell fenlight isn’t that small

**Comment by TimboZero** [comment] 2024-11-23 18:02
Yeah I stand corrected, the thing zips up real tight. Guess a lot of that 4MB is text ;)

**Comment by JDOG301** [comment] 2024-11-23 18:19
Sorry I have never downloaded an add on this way so I don’t know what to do. How do I put the zip file onto my FireStick and use it on Kodi?

**Comment by Tikipeter** [comment] 2024-11-23 18:41
The github.io address should work again in Kodi's file manager.

**Comment by peno64** [comment] 2024-11-23 18:49
installed from zip
working great
thx @Tikipeter

**Comment by JDOG301** [comment] 2024-11-23 19:05
> The github.io address should work again in Kodi's file manager.

I installed it all now but when I select a link none of them work for some reason.

**Comment by anguisviridis** [comment] 2024-11-23 19:36
Thank you very much!

**Comment by maildeamon** [comment] 2024-11-23 19:54
thnxx hard to see you go.

**Comment by GiitLew** [comment] 2024-11-23 20:24
> The github.io address should work again in Kodi's file manager.

Thank you for your creation Tikipeter king of kings

**Comment by LatItude98** [comment] 2024-11-23 21:26
I totally understand your decision. 
I unfortunately just had a few minutes to check in on my room. Hopefully since I am reading this quickly while at work I may have missed something .
If not it looks as I only have 4 hrs remaining to at the least DL the final upgraded zip. 
any chance of extending the 24 hr period by a few hours? If not I am sure a teammate will have it but I always prefer getting the new in box version of things when possible. 

Thanks so much for you contributions 
Lat

**Comment by TwilightMercy** [comment] 2024-11-23 21:47
> > Any chance for one last Fen 3.2.31 RD compatibility update?
> 
> Done.
> 

Thank you very much for EVERYTHING

**Comment by Gabba35** [comment] 2024-11-23 22:54
Hi Tikipeter,

Upgraded to the new version, thanks so much for all of your efforts over several years, they are greatly appreciated. It's changed how we do tv and movies.

I've tried to download a few season packs to my harddrive but can't seem to do that since the update to version 2.0.01. Is it possible to fix? Or is it just a side effect?

It's only a minor issue but thought I'd raise before you sign off forever.

**Comment by Tikipeter** [comment] 2024-11-24 01:02
>What does the name FEN stand for?

Furk & EasyNews. They were the original providers offered by Fen many years ago.

>Hi desperately trying to redownload fen lite before irs gone but im a rookie and struggling,

I'll keep the page up for 2 days. Also, the github.io kodi file manager source is working again. 

>I've tried to download a few season packs to my harddrive but can't seem to do that since the update to version 2.0.01. Is it possible to fix? Or is it just a side effect?

I'm about to have a look. I needed to make the fix for RD quickly, so things have been overlooked like this.

Maybe I can fix it in time, maybe not.

**Comment by Tikipeter** [comment] 2024-11-24 02:42
There will be another version `2.0.02` added to the tikipeter.gtithub.io/packages source to fix a couple of these niggling issues (pack downloads etc). Once you see that version in the packages, you can install it from zip and it will update Fen Light.

You will not be able to update through Fen Light as you did in the past, as that was disabled.

**Comment by YungZanji** [comment] 2024-11-24 03:09
“This will allow me to safely delete this github account, which I will do 24 hours after the final release.”

Does this mean that it won’t be available to be forked or downloaded from after 24hours?

**Comment by Gabba35** [comment] 2024-11-24 03:51
Amazing, thanks so much again!

**Comment by minicoz** [comment] 2024-11-24 04:12
Thank you for everything Tiki! 

And thank you for the red hat ;) we won

**Comment by Projectal374** [comment] 2024-11-24 04:50
hello, why don't you archive the repository instead? 

Thank you for Fen Lite.

**Comment by Tikipeter** [comment] 2024-11-24 07:18
>hello, why don't you archive the repository instead?

Wouldn't achieve what I want to achieve.

**Comment by YungZanji** [comment] 2024-11-24 07:22
> > hello, why don't you archive the repository instead?
> 
> Wouldn't achieve what I want to achieve.

Thanks for fen lite and fen. It would be awesome to have it archived so that we can continue to access it after you’ve left.

**Comment by Tikipeter** [comment] 2024-11-24 07:43
Download the zip. I've been saying that for days now. It's all archived in there.

**Comment by hcgiub001** [comment] 2024-11-24 13:17
Don't go, you know the IPTV thing is mainly to do with money. You are a much easier target to go after if they wanted to go after you than RD. He was making 32 million euros or something , of course they had a target on his head. Even if they wanted to go after you they would give you a warning first or even get github to take you down.
Even before they go after you they would go after Stremio. You'll have plenty of warning to get out the way.
I liked trying to improve Fen Lite. I can't go back to the sub reddit without you. Even though you've sent the code so it can't update, you can do what you did before.
Can you just take some time off and think about it? Just don't make it final, see what happens in the scene. You didn't even make a penny from this. they could have tried going after you so long ago!!!!!!
DON'T GO!
DON'T DELETE YOUR GITHUB AND MAKE IT FINAL!

**Comment by hcgiub001** [comment] 2024-11-24 13:19
I'm deleting my subreddit and github if you go

**Comment by hcgiub001** [comment] 2024-11-24 13:58
I even figured out the code you use to try to match season and episode for the anime! before this RD thing happened , I was so excited. 

[source_utils.txt](https://github.com/user-attachments/files/17893434/source_utils.txt)

this is only after I'm starting to learn how easy it is to modify things

Already it picks up much more results.

I learnt of https://sneedex.moe/ . they are a very friendly bunch who are hardcore anime enthusiasts that catalogue the best quality for anime with torrents in Nyaa, they have an API and they are so nice on their discord
https://sneedex.moe/

I wanted to use DMM and make a hashlist, then each anime I was going to make sure Fen Lite could match it's weird naming scheme, the pattern list I was going to make sure it's the minimum added so they are flexible.
It would have been amazing and I intended to create a trakt list of this. then maybe add it in a section in Fen Lite.
I only watch one anime a week. I'm not in Kodi to watch stuff, just to tinker and see my work come to life. You've been the inspiration to this. Just as I was abut to realise my potential you leave and worst of all leave because of the post I made.

I discovered 

var cinemetaUrls = {
    'movie': 'https://cinemeta.strem.io/stremioget/stremio/v1/q.json?b=eyJwYXJhbXMiOltudWxsLHt9XSwibWV0aG9kIjoibmFtZXMubW92aWUiLCJpZCI6MSwianNvbnJwYyI6IjIuMCJ9',
    'series': 'https://cinemeta.strem.io/stremioget/stremio/v1/q.json?b=eyJwYXJhbXMiOltudWxsLHt9XSwibWV0aG9kIjoibmFtZXMuc2VyaWVzIiwiaWQiOjEsImpzb25ycGMiOiIyLjAifQ==',
}

stremio app cinemata create this, it matches names with IMDB numbers. 
the user on here
https://www.reddit.com/r/StremioAddons/comments/1dtvjmk/comment/lvbmlve/

relies on it. and uses it to get the imdb list from sites like bestsimilar, the "more like this" was such a good addition that we could have used this list in Fen Lite, It's a single API call after you scrape the bestsimilar site, You could have even just add the updated list on each new update so we never even need to make a call to the cinemata site, so it's literally scraping sites like best similar then using the list we have installed in fen lite to match it. if it finds it then you can do what you did with IMDB site and make calls to TMDB.

I had so many ideas I wanted to ask you but had so many already listed. I really enjoyed working on this. No other developer gave me inspiration or wanted to work on it. You inspire others. You even got the other dev to come back and forming a good relationship with Umbrella.

They will just get rid of your github. and Kodi is the last on target before stremio. The raids on kodi people have been done long before RD thing.

This is 7 years ago
https://www.reddit.com/r/kodi/comments/5ssdhv/five_arrests_in_fully_loaded_kodi_streaming_box/

PETER DON'T GO! please just think about it. I wanted to go after the new year ended but couldn't even wake up today and face the world since I can't work on anything. You don't even have to work on Fen Lite as much or just lay back for a little while to look at what is happening. Just close the issues. You've been like a father figure in all this and I've come to you for advice. I even tried hard to get you 3 devs working together. The community at the subreddit was going well. I was the one who got in contact with penguin in elfhosted then messaged kodifitswell to get in contact with penguin to get zilean open.

KODI is dead without you, at least for me. I could have even one day learnt enough to add something of value. You still have to help create a way so widgets work better!

please think about it. Before you are at risk you'll have enough warning. and the world cares about those that are making money from this. They don't go after small fish that don't even take an affiliated link! RD is a multi million dollar empire, that raid was for 32 million euros. YOU MAKE NOTHING

take off the christmas and enjoy it with your family. I could work on the anime like I wanted. it would be complete when new years happen and you can come back. back up your github.
I know you live this, it's your passion and it got to much, but you'll miss it and you are leaving but nothing changed. they've always target people that are making money. not developers that are not doing anything illegal. No arrests were made in RD, no fines were made, no names were given out.

I'm sorry for my ramblings. You going has left a piece of me. I've already destroyed on website before I met Kodi and Fen Lite. Will you give a way that you can come back after the christmas, we're just some people enjoying our passion and I was surprised how much people cared about you and Fen Lite, I thought most were just assholes but they really wanted the best for you. 

Every gets spooked out, but being exhausted from nonestop work affected your ability to put risk on this. You even have other developers. 
Peter don't leave please.

**Comment by hcgiub001** [comment] 2024-11-24 14:21
Kodi isn't the one who got RD, it was Stremio, it's still stremio now. People are even moving away from Kodi for stremio , they know this. stremio will one day have enough that kodi would be less useful , I don't care, kodi will have a loyal fan base that understand what it adds. we can have our little group. They will go after stremio before they ever try on Kodi.
Stremio Dev tried copying Kodi, they have a main stremio and then they have a addons4stremio, but the lead dev himself is on both, he added mdblist

https://www.reddit.com/r/StremioAddons/comments/1guj5eo/mdblist_addon_updated/

this is the lead developer of stremio that has openly making it obvious that they are linking to addons, this is stremio that is on tiktok not the overly complicated and hard to use Kodi. who do you think they will take down first? if they ever tried to?

Over their they are jubilant about this they are having fun , if anything they are more of a target. you've already seen how many users on Kodi say they have started to like stremio better, good for them. I like Kodi and I like the community and the flexibility. can you stay Peter? you are just tired and got spooked. even the issues you been getting slowed down because Fen Lite is working so well. it would be calmer and I don't rely on you as much to work on features. I have my own ideas. Now I know how  powerful it is I can really start to learn Python and the links you provided about how to get started on addons.

Stremio will go down first if what you think will come to fruition, you then back down. they have no reason to bother with kodi developers right now. I've always said kodi long term won't be taking in the grandmas and the laymen. it's more for technically minded and so it will never do what stremio has done. You don't create something like Fen Lite if you are not logical, i'm a logical person to. even reading what I said you think I'm not proving by facts? 7 years ago they raided XBMC people who made money on this. You are not worth anyones time to prosecute. the raid must have cost millions to work out and implement. they don't spend millions so they can go after a guy with a family that hasn't done anything illegal and likes to work on his code. they will give you a desist warning first. they did that with RD. RD knew what it was doing and carried on and then when told to stop have implemented enough so they leave them alone.
Will you please reconsider?

**Comment by Tikipeter** [comment] 2024-11-24 20:27
@hcgiub001 I wrote you a reply on reddit yesterday. Give it a read.

@ivarbrandt  It was great seeing the giant and speedy strides you took when starting your skinning journey. You overtook anything I could help you with VERY quickly! I love your skins, and so do many it seems. It was a pleasure to get to know you some. Awesome guy, and now a great skin dev. :)

**Comment by JCSHillc** [comment] 2024-11-25 20:13
Hi Peter, I'm an absolute numbskull with this - I've downloaded the latest update via Kodi > Add Ons > Install from zip file but I'm still getting "no results" when I search. All Debrid and Coco scrapers both enabled. 

What am I missing? 

PS Thanks for everything

**Comment by Flashback944** [comment] 2024-11-25 22:06
Thanks for all your hard work and effort over the years:)

Fen/Fen Lite have been fantastic to use!

Good luck for the future:)

**Closed** 2024-11-26 07:29 UTC
Labels: Information

**Comment by Shredder5262** [comment] 2024-11-29 23:30
How long will fen light continue to work without your support?
Also, thank you for your support, I just only recently started using fenlight in the last year-ish, but I can tell you're very adored by the community.

**Comment by betatester3016** [comment] 2024-12-02 16:21
Thanks for all the time and effort you have devoted on this addon. Sorry to see you go. Take care and safe travels.
