### ISSUE TITLE
v1.0.47 movies>in progress is blank 

### ISSUE THREAD

**Issue by Liquidrag** [Tikipeter/tikipeter.github.io#33] opened 2024-04-17 14:23 UTC
I'm not sure if this is by design because you added the option  to add your own Trakt client ID and Secret but it is blank. Adding my own ID and Secret fixes it but just wanted to give you a heads up. Thnx for the addon and continued updates.

**Comment by Tikipeter** [comment] 2024-04-17 16:08
No, it's not by design. I had the currently used id and secret used as the default settings for both.

Are you using the myaccounts manager.

**Comment by xyzfre** [comment] 2024-04-17 16:44
This is a good option for the API keys.When I saw that I put my own TMDB right away,, I haven't had a chance yet to add my Trakt API,Thank you @Tikipeter hopefully in the future we can get the option for are own Fanart.TV API key

**Comment by xyzfre** [comment] 2024-04-17 23:37
@Tikipeter I added my own Trakt API key, everything is working, except My in progress movies show up blank

**Comment by Tikipeter** [comment] 2024-04-17 23:59
You entered the Client ID and Client Secret?

**Comment by xyzfre** [comment] 2024-04-18 00:13
> You entered the Client ID and Client Secret?

Yes, I have enter both and check my Trakt account and it shows it's connected.

**Comment by Tikipeter** [comment] 2024-04-18 01:06
Should be fixed with version just released.

**Comment by xyzfre** [comment] 2024-04-18 01:43
It's working, but I had to re-authorize my Trakt account,,LEGEND 💯

**Comment by Liquidrag** [comment] 2024-04-18 04:12
@Tikipeter Sorry i've been gone all day. I am not using account manager and I see that you have pushed an update, Thank you

**Comment by Tikipeter** [comment] 2024-04-18 04:26
It should be working now.

**Comment by KalAvroniev** [comment] 2024-04-18 10:27
I'm having the same issue and I'm using the Account Manager. 
It used to work fine on 1.0.46 and then the last two versions (1.0.47 and 1.0.48) have broken this.
Clearing the trakt cache does not help.

Authenticating from within FenLight did not work either. Clearing the cache worked partially but was not able to get the full list of episodes.
Shutting Kodi and starting it again did not work either.
Clearing all cache, nothing.
Kodi log shows 401 Client Error: Unauthorised.

The only solution was to revoke Trakt from Account manager and then authorise in FenLight.

Is account manager going to be supported or do they need to update what they are doing with the credentials?

**Comment by Tikipeter** [comment] 2024-04-18 14:03
As far as I'm aware they have already updated account manager to come inline with the latest version of Fen Light.

If you are using account manager, I hope you understand that addon was changing code in Fen Light to support using their Trakt account within Fen Light. A find/replace sort of thing. So, if you were using account manager for Trakt, then you weren't authorizing Fen Light's Trakt credentials. They were inserting their client id and client secret into the Fen Light code.

In the end, making the client ID and client secret setting values will likely make things easier for the myaccounts manager dev according to a quick look of the code used.

**Closed** 2024-04-19 22:57 UTC
